"""add analyst_feedback table

Revision ID: a4fc36b9ad5f
Revises: cca7e425ef0a
Create Date: 2026-08-25 22:27:52.525505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a4fc36b9ad5f'
down_revision: Union[str, None] = 'cca7e425ef0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS feedback_decision")
    op.create_table('analyst_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('ACCEPT', 'MODIFY', 'REJECT', name='feedback_decision'), nullable=False),
    sa.Column('corrected_recommendation', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_feedback_actor'), 'analyst_feedback', ['actor'], unique=False)
    op.create_index(op.f('ix_analyst_feedback_case_id'), 'analyst_feedback', ['case_id'], unique=False)
    op.create_index(op.f('ix_analyst_feedback_created_at'), 'analyst_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyst_feedback_investigation_id'), 'analyst_feedback', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyst_feedback_investigation_id'), table_name='analyst_feedback')
    op.drop_index('ix_analyst_feedback_created_at', table_name='analyst_feedback')
    op.drop_index(op.f('ix_analyst_feedback_case_id'), table_name='analyst_feedback')
    op.drop_index(op.f('ix_analyst_feedback_actor'), table_name='analyst_feedback')
    op.drop_table('analyst_feedback')
    op.execute("DROP TYPE IF EXISTS feedback_decision")
    # ### end Alembic commands ###